export const PROMPTS = [
    'Sunset Photo 🌇',
    'Cat Photo 🐱',
    'Boba Photo with Friends 🧋',
    'Funniest Photo ✨',
    'Best 0.5 🕶️',
    'Favorite Book 📚',
    'Travel Memory ✈️',
    'Coffee Time ☕',
    'Selfie Saturday 🤳',
    'Nature Walk 🌳',
    'Celebration Moment 🎉',
    'Work Setup 💻',
    'Fitness Journey 🏋️‍♀️',
    'Cooking Adventure 🍳',
    'Movie Night 🎬',
    'Hidden Talent 🎨',
    'Morning Routine ☀️',
    'Workspace Essentials 📎',
    'Pet Love 🐾',
    'Music Mood 🎵',
    'DIY Project 🔨',
    'Family Time 👨‍👩‍👧‍👦',
    'Hobby Showcase 🎸',
    'Sunrise Photo 🌅',
    'Tech Gadgets 📱',
    'Favorite Quote 📜',
    'Fitness Progress 💪',
    'Meal Prep 🥗',
    'Artistic Expression 🎭',
    'Gaming Setup 🎮',
    'Home Decor 🏡',
    // Add more prompts as needed
  ];